---
abstract: unknown
author:
  - 'LNATION <thisusedtobeanemail@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Metadata: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-TableContent
no_index:
  directory:
    - t
    - inc
provides:
  HTML::TableContent:
    file: lib/HTML/TableContent.pm
    version: '0.06'
  HTML::TableContent::Element:
    file: lib/HTML/TableContent/Element.pm
    version: '0.06'
  HTML::TableContent::Parser:
    file: lib/HTML/TableContent/Parser.pm
    version: '0.06'
  HTML::TableContent::Table:
    file: lib/HTML/TableContent/Table.pm
    version: '0.06'
  HTML::TableContent::Table::Caption:
    file: lib/HTML/TableContent/Table/Caption.pm
    version: '0.06'
  HTML::TableContent::Table::Header:
    file: lib/HTML/TableContent/Table/Header.pm
    version: '0.06'
  HTML::TableContent::Table::Row:
    file: lib/HTML/TableContent/Table/Row.pm
    version: '0.06'
  HTML::TableContent::Table::Row::Cell:
    file: lib/HTML/TableContent/Table/Row/Cell.pm
    version: '0.06'
requires:
  Carp: '1.22'
  HTML::Parser: '3.71'
  Moo: '1.001001'
  perl: '5.006'
resources:
  repository: https://github.com/ThisUsedToBeAnEmail/HTML-TableContent.git
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
